name: Azure DevOps workitem tagging
description: Action used for tagging specific work item with environment value
inputs:
  azure-pat:
    description: PAT
    required: true
  deploy_env:
    description: Environment to which changes were deployed
    required: true
runs: 
  using: composite
  steps:
    - shell: bash
      env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: echo ${{ github.token }}
    - env:
        GH_TOKEN: ${{ github.token }}
        AZURE_DEVOPS_EXT_PAT: ${{ inputs.azure-pat }}
      if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event != 'workflow_dispatch' }}
      shell: bash
      run: |
        az extension add --name azure-devops
        az devops configure --defaults organization=https://dev.azure.com/lukaszadamsielski0187  
        python /home/runner/work/workflows_tests/workflows_tests/scripts/script.py --commit-sha ${{ github.event.workflow_run.head_sha }} --deploy_env ${{ inputs.deploy_env }}
    # - id: failing_step
    #   continue-on-error: true
    #   shell: bash
    #   run: exit 0
    # - id: test_failure
    #   if: ${{ steps.failing_step.outcome == 'failure' }}
    #   shell: bash
    #   run: echo "Failed"
    # - id: test_success
    #   if: ${{ steps.failing_step.outcome == 'success' }}
    #   shell: bash
    #   run: echo "Success"
