name: Azure DevOps workitem tagging
description: Action used for tagging specific work item with environment value
inputs:
  gh-token:
    description: GitHub token necessary for interacting with GitHub CLI
    required: true
  azure-pat:
    description: PAT
    required: true
  deploy_env:
    description: Environment to which changes were deployed
    required: true
runs:
  using: composite
  steps:
    # - shell: bash
    #   env:
    #     EVENT_CONTEXT: ${{ toJSON(github.event) }}
    #   run: echo $EVENT_CONTEXT
    - env:
        GH_TOKEN: ${{ inputs.gh-token }}
        AZURE_DEVOPS_EXT_PAT: ${{ inputs.azure-pat }}
      if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.event != 'workflow_dispatch' }}
      shell: bash
      run: |
        python /home/runner/work/workflows_tests/workflows_tests/scripts/script.py --commit-sha ${{ github.event.workflow_run.head_sha }} --deploy_env ${{ inputs.deploy_env }}
    # - id: failing_step
    #   continue-on-error: true
    #   shell: bash
    #   run: exit 0
    # - id: test_failure
    #   if: ${{ steps.failing_step.outcome == 'failure' }}
    #   shell: bash
    #   run: echo "Failed"
    # - id: test_success
    #   if: ${{ steps.failing_step.outcome == 'success' }}
    #   shell: bash
    #   run: echo "Success"
