name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build
    types:
      - completed


jobs:
  get_secret:
    runs-on: ubuntu-latest
    environment: dev-com-ent-us
    outputs:
      azure-credentials: ${{ steps.get-secret.outputs.azure-credentials }}
    steps:
      - name: Get sectet
        id: get-secret
        shell: bash
        run: echo "azure-credentials=${{ vars.SECRET }}" >> "$GITHUB_OUTPUT"
  tag-azure-board-work-item:
    runs-on: ubuntu-latest
    needs: get_secret
    steps:
      - shell: bash
        run: echo "${{ needs.get_secret.outputs.azure-credentials }}"
      - uses: actions/checkout@v3
        name: Checkout repository
      - uses: ./.github/workflows/actions/ado_tag
        with:
          azure-pat: ${{ secrets.ADO_PAT }}
          deploy_env: apollo-dev