name: test

on:
  push:
    branches: [main]

jobs:
  get-pr-number-from-commit-message:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.step1.outputs.pr_number }}
    steps:
      - id: step1
        run: echo ${{ github.event.head_commit.message }}
      - run: echo "pr_number=${{ github.event.head_commit.message }}" >> "$GITHUB_OUTPUT"

  get-pr-number:
    runs-on: ubuntu-latest
    steps:
     - run: sudo apt-get update && sudo apt-get install jq
     - run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/LukaszSielski/workflows_tests/pulls/1 | jq -r .body

 
  